accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r"login/$", auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"signup/$", views.SignUp.as_view(), name="signup"),
]

posts/urls.py
from django.conf.urls import url

from . import views

app_name='posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(), name="all"),
    url(r"new/$", views.CreatePost.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    url(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
]

simplesocial/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^test/$", views.TestPage.as_view(), name="test"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^admin/", admin.site.urls),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^posts/", include("posts.urls", namespace="posts")),
    url(r"^groups/",include("groups.urls", namespace="groups")),
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>LiNKtern Social</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">
  </head>
  <body>
    <header>
      <nav class="navbar">
	       <a class="btn btn3" href="{% url 'home' %}" style="float:left;">LiNKterns</a>
         {% if user.is_authenticated %}
         <div class="ul">
          <div class="li">
	          <a class="btn btn3" href="{% url 'posts:all' %}">Posts</a>
	          <a class="btn btn3" href="{% url 'posts:create'%}">Create Posts</a>
            <a class="btn btn3" href="{% url 'groups:all'%}">Groups</a>
	          <a class="btn btn3" href="{% url 'groups:create' %}">Create Groups</a>
            <a class="btn btn3" href="{% url 'accounts:logout' %}">Log out</a>
          </div>
        </div>
        <div class="menu">
          <label onclick="closeNav()" class="cut" for="cut">
            <span>☰</span>
          </label>
          <input id="cut" class="hide" type="checkbox">
          <div>
            <div class="menu-columns">
              <div>
                <input id="flap-products" class="flap-checkbox hide" type="checkbox">
                <label class="flap-label" for="flap-products"><strong>Aircrafts</strong></label>
                <div>
                  <a href="#">Quinjets</a>
                  <a href="#">Fighters</a>
                  <a href="#">Passenger</a>
                  <a href="#">Cargo</a>
                  <a href="#">Helicopters</a>
                  <a href="#">Help &amp; support</a>
                </div>
              </div>
              <div>
                <input id="flap-developers" class="flap-checkbox hide" type="checkbox">
                <label class="flap-label" for="flap-developers"><strong>Military</strong></label>
                <div>
                  <a href="#">Guns</a>
                  <a href="#">Bombs</a>
                  <a href="#">Armours</a>
                </div>
              </div>
              <div>
                <input id="flap-work" class="flap-checkbox hide" type="checkbox">
                <label class="flap-label" for="flap-work"><strong>Fruits</strong></label>
                <div>
                  <a href="#">Cars</a>
                  <a href="#">Bikes</a>
                  <a href="#">Furniture</a>
                  <a href="#">Houses</a>
                </div>
              </div>
              <div>
                <input id="flap-work" class="flap-checkbox hide" type="checkbox">
                <label class="flap-label" for="flap-work"><strong>Clothes</strong></label>
                <div>
                  <a href="#">Cars</a>
                  <a href="#">Bikes</a>
                  <a href="#">Furniture</a>
                  <a href="#">Houses</a>
                </div>
              </div>
              <div>
                <input id="flap-work" class="flap-checkbox hide" type="checkbox">
                <label class="flap-label" for="flap-work"><strong>Customized</strong></label>
                <div>
                  <a href="#">Cars</a>
                  <a href="#">Bikes</a>
                  <a href="#">Furniture</a>
                  <a href="#">Houses</a>
                </div>
              </div>
              <div>
                <input id="flap-work" class="flap-checkbox hide" type="checkbox">
                <label class="flap-label" for="flap-work"><strong>Customized</strong></label>
                <div>
                  <a href="#">Cars</a>
                  <a href="#">Bikes</a>
                  <a href="#">Furniture</a>
                  <a href="#">Houses</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% else %}
          <ul class="nav">
            <li><a class="btn btn3" href="{% url 'accounts:login' %}">Login</a></li>
            <li><a class="btn btn3" href="{% url 'accounts:signup' %}">Sign Up</a></li>
          </ul>
        {% endif %}
     </nav>
  </header>

    <div class="container mycontent">
      {% block content %}

      {% endblock %}
    </div>
        {# <canvas id="canvas"></canvas>#}
  </body>
  <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script>
</html>

templates/index.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'simplesocial/css/index.css' %}">
{% block content %}
<br>
<br>
  <div class="col-md-8">
      <h4 class="card-title">Welcome to LiNKtern Soacial.</h4>
    <div class="card-block">
      <p>Please Login<strong> or </strong>sgin up to get started</p>
      
    </div>
  </div>
{% endblock %}

templates/test.html
{% extends "base.html" %}
{% block title %}
  Welcome
{% endblock %}
{% load staticfiles %}
{% block content %}
<link rel="stylesheet" href="{% static 'simplesocial/css/landing.css' %}">
<br><br>
  <div class="container">
    <h4>Welcome, <strong>{{user.username}}</strong>.</h4>
    <hr>
    <div class="row">
      <div class="col-md-6">
        <div class="card-header">
          <h4 class="card-title">Go checkout groups</h4>
        </div>
        <div class="card-block">
          <p>Where you can go find out what linkterns up to.</p>
        </div>
        <div class="card-footer">
          <a class="btn btn3" href="{% url 'groups:all' %}">Go to Groups</a>
        </div>
      </div>
      <hr>
      <div class="col-md-6">
        <div class="card-header">
          <h4 class="card-title">Go checkout Posts</h4>
        </div>
        <div class="card-block">
          <p>There are more than 10 billion cells in human body.</p>
        </div>
        <div class="card-footer">
          <a class="btn btn3" href="{% url 'posts:all' %}">Go to Posts</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
    <h4>thanks for checking out, come back soon!</h4>
  </div>
{% endblock %}